name: Build obsidian plugin

permissions:
  contents: write

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching any tag format

env:
  PLUGIN_NAME: cloud-atlas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Build
      id: build
      run: |
        npm install
        npm run build --if-present
        npm run dev-build --if-present
        mkdir ${{ env.PLUGIN_NAME }}
        cp manifest.json dist/
        cp styles.css dist/
        cp README.md dist/
        cp dist/main.js dist/manifest.json ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        ls dist/
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/main.js dist/manifest.json dist/main-debug.js dist/styles.css dist/README.md \
            ${{ env.PLUGIN_NAME }}.zip
